### ISSUE TITLE
Error with usemtl

### ISSUE THREAD

**Issue by oculushut** [chrispalazzolo/objtojs#2]
Similar problem as #1.  usemtl lines can appear after a f line.

OBJ can contain something like this:

```
f 93407//93407 93406//93406 93408//93408
usemtl Iron_man_leg:red
f 93430//93430 93428//93428 93429//93429
```

See line 308793 of the same [iron man file used in](http://tf3dm.com/3d-model/ironman-rigged-original-model--98611.html) #1 

The following is the error when this occurs in the file:

```
TypeError: Cannot set property 'use_material' of null
    at parseText ([MY DIRECTORY]\node_modules\objtojs\index.js:176:24)
    at [MY DIRECTORY]\node_modules\objtojs\index.js:44:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
```

**Comment by chrispalazzolo** [comment]
I had to go back in and rework how it was collecting the data.  The js object returned should more closely reflect the obj file format.  It now preserves the element order as it is parsing the data.  My latest changes have been pushed up.  The file you provided helped me quite a bit.  Thanks.
